sudo: required

# Tell Travis we need docker
services:
  - docker

# Tell Travis to build our docker project
before_install:
  - docker build -t netblue/docker-react -f Dockerfile.dev .

# Because the default npm run test behavior is to sit and wait for user input, we need to add -- --coverage to the npm
# command to make it run and exit
script:
  - docker run -e CI=true netblue/docker-react npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env-1"
  #Bucket name is the S3 disk that is on your ElasticBeanstalk instance
  bucket_name: "elasticbeanstalk-us-west-2-277807926920"
  bucket_path: "docker-react"
  # Tell Travis only to deploy when we push to master
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
